### ISSUE TITLE
is.gd shortener is blocking vpn connections

### ISSUE THREAD

**Issue by ineeee** [FrozenPigs/Taigabot#12]
as adrift pointed out yesterday, the url shortener used by taiga is blocking vpn connections. i don't have his provider to debug if the server is sending a 403 code or if its just some general connection error.

this could be fixed by either replacing is.gd or avoiding shortening short links (maybe a 30 char limit?) current is.gd shortened links are always between 18 and 21 characters.

i emailed the is.gd team to ask if they block vpn connections.

**Comment by UMLAUTaxl** [comment]
They're neither blocking express vpn nor nord vpn.

**Comment by ineeee** [comment]
closing because no one has had any issues lately.

the is.gd people emailed me back explaining they only block particularly abusive ips, nothing against a vpn.
